-- Query para insertar productos de muestra en la base de datos
INSERT INTO Products (name, description, price, imageUrl, category) VALUES
('Mermelada de Frutilla', 'Hecha con frutas orgánicas de la región.', '$800', 'https://www.bing.com/images/search?view=detailV2&ccid=s2Pbt8aM&id=B56C28F1889C4C438DB3ABE1BEF062836BC5A033&thid=OIP.s2Pbt8aMZ89BNRupitAL3gHaEK&mediaurl=https%3a%2f%2fmedia.airedesantafe.com.ar%2fp%2f2fe4a2e909f0c089160ecdbad8748b33%2fadjuntos%2f268%2fimagenes%2f003%2f780%2f0003780168%2f1200x0%2fsmart%2fimagepng.png&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.b363dbb7c68c67cf41351ba98ad00bde%3frik%3dM6DFa4Ni8L7hqw%26pid%3dImgRaw%26r%3d0&exph=675&expw=1200&q=mermelada+de+frutilla&simid=608035669405729296&FORM=IRPRST&ck=8CD3DE7F9B4AFA457D4D5B6552D9E2D6&selectedIndex=2&itb=0&ajaxhist=0&ajaxserp=0', 'Alimentos'),
('Cartera tejida artesanal', 'Cartera hecha a mano por artesanos locales.', '$4.500', 'https://www.bing.com/images/search?view=detailV2&ccid=GMEVzri3&id=3E27AA6FFE168B17BAEB6DD3EDE37283FFA53B95&thid=OIP.GMEVzri3iCniTQcNlw14_QHaFj&mediaurl=https%3a%2f%2fi.pinimg.com%2foriginals%2f8c%2f0f%2f55%2f8c0f55a8cf3d0bc0f516ad99a68b2f8e.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.18c115ceb8b78829e24d070d970d78fd%3frik%3dlTul%252f4Ny4%252b3TbQ%26pid%3dImgRaw%26r%3d0&exph=600&expw=800&q=Cartera+tejida+artesanal&simid=608039358772414289&FORM=IRPRST&ck=33091B448DDAC005EC69EC859AEBCEB3&selectedIndex=267&itb=0&qft=+filterui%3aphoto-photo&ajaxhist=0&ajaxserp=0', 'Textiles'),
('Shampoo sólido natural', 'Sin químicos ni parabenos. Ideal para cabello seco.', '$2.000', 'https://www.bing.com/images/search?view=detailV2&ccid=EkVPabEH&id=42622D6EBAD9B40035CA45B90C3410F434266372&thid=OIP.EkVPabEHtp0TCZCsbsitEAHaE8&mediaurl=https%3a%2f%2fwww.nexofin.com%2farchivos%2f2021%2f04%2fshampoo-solido-come-si-usa-scaled-e1613394303744.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.12454f69b107b69d130990ac6ec8ad10%3frik%3dcmMmNPQQNAy5RQ%26pid%3dImgRaw%26r%3d0&exph=854&expw=1280&q=Shampoo+s%c3%b3lido+natural&simid=607996112742525782&FORM=IRPRST&ck=E593BC8E6C54286BB868F3FA7A71BAF7&selectedIndex=4&itb=0&ajaxhist=0&ajaxserp=0', 'Cosmética Natural'),
('Pan casero integral', 'Pan recién horneado con harina orgánica.', '$700', NULL, 'Alimentos'),
('Aro de cerámica artesanal', 'Aros pintados a mano, únicos e irrepetibles.', '$1.200', NULL, 'Artesanías'),
('Jabón de lavanda', 'Jabón artesanal con aceite esencial de lavanda.', '$600', NULL, 'Cosmética Natural'),
('Bolso de lona reciclada', 'Confeccionado con telas reutilizadas, resistente y ecológico.', '$3.200', NULL, 'Textiles'),
('Miel pura', 'Miel 100% natural, extraída en campos locales.', '$1.800', NULL, 'Alimentos'),
('Collar de macramé', 'Diseño boho-chic hecho a mano con hilo de algodón.', '$2.000', NULL, 'Artesanías'),
('Crema facial natural', 'Hidratante con aloe vera y karité, sin fragancias sintéticas.', '$2.500', NULL, 'Cosmética Natural'),
('Camiseta orgánica estampada', 'Diseños exclusivos sobre algodón orgánico.', '$4.000', NULL, 'Textiles'),
('Alfajor de maicena artesanal', 'Relleno con dulce de leche casero y coco rallado.', '$500', NULL, 'Alimentos'),
('Cuadro en madera reciclada', 'Obra decorativa hecha con materiales reutilizados.', '$6.000', NULL, 'Artesanías'),
('Desodorante natural en barra', 'Efectivo, libre de aluminio y amigable con la piel.', '$1.200', NULL, 'Cosmética Natural'),
('Mate artesanal calabaza', 'Forrado en cuero, pintado a mano por emprendedores.', '$3.000', NULL, 'Artesanías'),
('Té de hierbas serranas', 'Blend natural de hierbas cultivadas en montaña.', '$900', NULL, 'Alimentos'),
('Riñonera con tela estampada', 'Práctica y colorida, perfecta para ferias o salidas.', '$2.800', NULL, 'Textiles'),
('Acondicionador sólido natural', 'Repara e hidrata el cabello, sin siliconas.', '$1.800', NULL, 'Cosmética Natural'),
('Velas aromáticas de soja', 'Velas ecológicas con fragancias naturales.', '$1.300', NULL, 'Artesanías'),
('Yerba mate agroecológica', 'Secado natural sin humo, sabor suave.', '$2.200', NULL, 'Alimentos'),
('Tarta de zapallo casera', 'Tarta saludable con masa integral y vegetales frescos.', '$1.200', NULL, 'Alimentos'),
('Bufanda tejida a mano', 'Lana pura de oveja, ideal para el invierno.', '$3.000', NULL, 'Textiles'),
('Aceite corporal de almendras', 'Nutre la piel profundamente con aroma suave.', '$2.300', NULL, 'Cosmética Natural'),
('Cuenco de barro cocido', 'Hecho a mano, ideal para servir salsas o snacks.', '$950', NULL, 'Artesanías'),
('Chips de batata deshidratada', 'Snack saludable y crocante, sin conservantes.', '$600', NULL, 'Alimentos'),
('Pantalón de lino artesanal', 'Cómodo, fresco y teñido naturalmente.', '$4.800', NULL, 'Textiles'),
('Bálsamo labial natural', 'Con manteca de karité y aceites esenciales.', '$850', NULL, 'Cosmética Natural'),
('Posavasos de madera reciclada', 'Set de 4 piezas con diseños grabados a mano.', '$1.100', NULL, 'Artesanías'),
('Galletas de avena y miel', 'Sin azúcar refinada, ideales para meriendas.', '$700', NULL, 'Alimentos'),
('Top de algodón orgánico', 'Tejido a mano con técnicas sostenibles.', '$3.500', NULL, 'Textiles'),
('Crema corporal de caléndula', 'Alivio para piel sensible y enrojecida.', '$1.900', NULL, 'Cosmética Natural'),
('Llavero de cuero trabajado', 'Artesanía con iniciales personalizadas.', '$600', NULL, 'Artesanías'),
('Granola artesanal con frutos secos', 'Perfecta para desayuno o snack saludable.', '$950', NULL, 'Alimentos'),
('Falda bordada a mano', 'Con detalles florales tradicionales.', '$4.200', NULL, 'Textiles'),
('Mascarilla capilar nutritiva', 'Fortalece el cabello con ingredientes naturales.', '$2.400', NULL, 'Cosmética Natural'),
('Florero cerámico esmaltado', 'Color tierra, diseño rústico y elegante.', '$2.000', NULL, 'Artesanías'),
('Pickles de pepino caseros', 'Conservados en vinagre de manzana orgánico.', '$1.100', NULL, 'Alimentos'),
('Camisa de algodón natural', 'Diseño unisex con botones de coco.', '$5.000', NULL, 'Textiles'),
('Perfume sólido artesanal', 'Fragancia suave con cera de abeja y aceites esenciales.', '$1.500', NULL, 'Cosmética Natural'),
('Decoración en macramé', 'Ideal para colgar en paredes o ventanas.', '$2.600', NULL, 'Artesanías');
