const products = [
  // ALFAJORES
  {
    id: 1,
    name: "Alfajor Bonobón",
    img: "/uploads/CarruselInicio/AlfBonobon.png",
    description: "Doble capa de dulce de leche...",
    price: 8000,
    stock: 10,
    offert: 0,
    tags: ["Alfajor", "Dulce de leche", "Chocolate", "Galletita"],
    modalId: "modalAlfBon",
    modalDescription: "Doble capa de dulce...",
    type: "Alfajores"
  },
  {
    id: 2,
    name: "Alfajor Bonobón",
    img: "/uploads/CarruselInicio/AlfBonobon.png",
    description: "Doble capa de dulce de leche entre galletas suaves con cobertura de chocolate con maní.",
    price: 8000,
    stock: 10,
    offert: 0,
    tags: ["Alfajores", "Dulce de leche", "Chocolate", "Maní"],
    modalId: "modalAlfBon",
    modalDescription: "Doble capa de dulce de leche entre galletas suaves, bañado en chocolate con maní picado. Una explosión de sabor clásico.",
    type: "Alfajores"
  },
  {
    id: 3,
    name: "Alfajor Coco Dulce",
    img: "/uploads/CarruselInicio/AlfCocoDulce.png",
    description: "Relleno de dulce de leche con cobertura de coco rallado.",
    price: 7500,
    stock: 10,
    offert: 0,
    tags: ["Dulce de leche", "Coco", "Alfajores"],
    modalId: "modalAlfCoco",
    modalDescription: "Un delicioso alfajor relleno de dulce de leche cubierto por una capa de coco rallado. Dulzura y frescura en un solo bocado.",
    type: "Alfajores"
  },
  {
    id: 4,
    name: "Alfajor de Maicena",
    img: "/uploads/CarruselInicio/AlfMaicena.png",
    description: "Galletas de maicena rellenas de dulce de leche y espolvoreadas con coco.",
    price: 6800,
    stock: 10,
    offert: 0,
    tags: ["Maicena", "Dulce de leche", "Coco", "Alfajores"],
    modalId: "modalMaicena",
    modalDescription: "Clásico alfajor argentino de maicena con dulce de leche y coco. Ideal para acompañar una merienda.",
    type: "Alfajores"
  },
  {
    id: 5,
    name: "Alfajor Chocolate Amargo",
    img: "/uploads/CarruselInicio/AlfChocoAmargo.png",
    description: "Relleno de dulce de leche y bañado en chocolate 70%.",
    price: 8200,
    stock: 10,
    offert: 0,
    tags: ["Chocolate amargo", "Dulce de leche", "Alfajores"],
    modalId: "modalChocoAmargo",
    modalDescription: "Para los amantes del chocolate intenso: alfajor relleno con dulce de leche y cobertura de chocolate amargo al 70%.",
    type: "Alfajores"
  },
  // TORTAS
  {
    id: 6,
    name: "Lemonpie",
    img: "/uploads/CarruselInicio/Lemonpie.png",
    description: "Base de masa quebrada...",
    price: 12000,
    stock: 5,
    offert: 0,
    tags: ["Limón", "Merengue", "Crema", "Masa"],
    modalId: "modalLemonpie",
    modalDescription: "Base crocante...",
    type: "Tortas"
  },
  {
    id: 7,
    name: "Chocotorta",
    img: "/uploads/CarruselInicio/Chocotorta.png",
    description: "Capas de galletitas de chocolate y crema de dulce de leche con queso crema.",
    price: 10000,
    stock: 5,
    offert: 0,
    tags: ["Chocolate", "Dulce de leche", "Queso crema", "Galletitas"],
    modalId: "modalChocotorta",
    modalDescription: "Capas de galletitas de chocolate y crema de dulce de leche con queso crema.",
    type: "Tortas"
  },
  {
    id: 8,
    name: "Torta Oreo",
    img: "/uploads/CarruselInicio/TortaOreo.png",
    description: "Base húmeda de chocolate con crema de Oreo y cobertura crocante.",
    price: 11000,
    stock: 5,
    offert: 0,
    tags: ["Oreo", "Chocolate", "Crema", "Torta"],
    modalId: "modalOreo",
    modalDescription: "Torta húmeda con capas de crema de Oreo, base de chocolate y decoración crocante.",
    type: "Tortas"
  },
  {
    id: 9,
    name: "Selva Negra",
    img: "/uploads/CarruselInicio/SelvaNegra.png",
    description: "Bizcochuelo de chocolate, cerezas y crema.",
    price: 10500,
    stock: 5,
    offert: 0,
    tags: ["Chocolate", "Cereza", "Crema", "Bizcochuelo"],
    modalId: "modalSelva",
    modalDescription: "Típica torta con capas de bizcochuelo de chocolate, cerezas y crema batida.",
    type: "Tortas"
  },
  {
    id: 10,
    name: "Tarta Frutal",
    img: "/uploads/CarruselInicio/TartaFrutal.png",
    description: "Base de masa con crema pastelera y frutas frescas.",
    price: 9500,
    stock: 5,
    offert: 0,
    tags: ["Frutas", "Crema pastelera", "Masa", "Tarta"],
    modalId: "modalFrutal",
    modalDescription: "Tarta clásica con crema pastelera suave y frutas frescas de estación.",
    type: "Tortas"
  },
  {
    id: 11,
    name: "Tiramisú Clásico",
    img: "/uploads/CarruselInicio/Tiramisu.png",
    description: "Bizcochuelo embebido en café con crema mascarpone.",
    price: 12500,
    stock: 5,
    offert: 0,
    tags: ["Torta", "Café", "Mascarpone", "Bizcochuelo", "Cacao"],
    modalId: "modalTiramisu",
    modalDescription: "Delicado postre italiano con capas de bizcochuelo al café y suave crema mascarpone.",
    type: "Tortas"
  },
  {
    id: 12,
    name: "Red Velvet",
    img: "/uploads/CarruselInicio/RedVelvet.png",
    description: "Bizcochuelo rojo aterciopelado con crema de queso.",
    price: 13000,
    stock: 5,
    offert: 0,
    tags: ["Torta", "Cacao", "Colorante", "Queso crema", "Vainilla"],
    modalId: "modalRedVelvet",
    modalDescription: "Elegante torta de color rojo intenso con crema de queso suave, ideal para ocasiones especiales.",
    type: "Tortas"
  },
  {
    id: 13,
    name: "Cheesecake de Frutos Rojos",
    img: "/uploads/CarruselInicio/CheesecakeFrutosRojos.png",
    description: "Base de galletitas con crema de queso y salsa de frutos rojos.",
    price: 13500,
    stock: 5,
    offert: 0,
    tags: ["Torta", "Queso crema", "Frutillas", "Arándanos", "Galletitas"],
    modalId: "modalCheesecakeRojos",
    modalDescription: "Cheesecake suave y cremoso con un toque ácido de frutos rojos frescos.",
    type: "Tortas"
  },
  // HUEVOS DE PASCUA
  {
    id: 14,
    name: "Huevo Pascua Oreo",
    img: "/uploads/CarruselInicio/HuevoOreo.png",
    description: "Chocolate relleno con oreo...",
    price: 15000,
    stock: 5,
    offert: 0,
    tags: ["Chocolate", "Oreo", "Pascua"],
    modalId: "modalHuevoOreo",
    modalDescription: "Chocolate relleno de oreo...",
    type: "Huevos"
  },
  {
    id: 15,
    name: "Huevo Kinder",
    img: "/uploads/CarruselInicio/HuevoKinder.png",
    description: "Chocolate con leche y centro cremoso estilo Kinder.",
    price: 16000,
    stock: 5,
    offert: 0,
    tags: ["Chocolate con leche", "Relleno cremoso", "Kinder", "Huevo de Pascua"],
    modalId: "modalKinder",
    modalDescription: "La textura suave del chocolate con leche y el sabor único del relleno tipo Kinder en forma de huevo.",
    type: "Huevos"
  },
  {
    id: 16,
    name: "Huevo Nutella",
    img: "/uploads/CarruselInicio/HuevoNutella.png",
    description: "Chocolate relleno con crema Nutella y crocante de avellanas.",
    price: 17000,
    stock: 5,
    offert: 0,
    tags: ["Nutella", "Chocolate", "Avellanas", "Huevo de Pascua"],
    modalId: "modalNutella",
    modalDescription: "Relleno irresistible de Nutella con crocante de avellanas dentro de un cascarón de chocolate.",
    type: "Huevos"
  },
  // CUPCAKES
  {
    id: 17,
    name: "Cupcake Red Velvet",
    img: "/uploads/CarruselInicio/CupRedVelvet.png",
    description: "Bizcocho rojo con frosting de queso crema.",
    price: 4500,
    stock: 10,
    offert: 0,
    tags: ["Red velvet", "Queso crema", "Cupcake"],
    modalId: "modalCupRed",
    modalDescription: "Cupcake esponjoso de Red Velvet con un cremoso frosting de queso. Elegante y delicioso.",
    type: "Cupcakes"
  },
  {
    id: 18,
    name: "Cupcake de Vainilla y Dulce de Leche",
    img: "/uploads/CarruselInicio/CupcakeVainilla.png",
    description: "Bizcochuelo de vainilla con corazón de dulce de leche.",
    price: 4000,
    stock: 10,
    offert: 0,
    tags: ["Vainilla", "Dulce de leche", "Cupcake", "Mini torta"],
    modalId: "modalCupVainilla",
    modalDescription: "Delicioso y suave bizcochuelo con relleno de dulce de leche y cobertura cremosa.",
    type: "Cupcakes"
  },
  {
    id: 19,
    name: "Cupcake de Limón y Amapola",
    img: "/uploads/CarruselInicio/CupcakeLimon.png",
    description: "Bizcochuelo cítrico con semillas de amapola y glaseado.",
    price: 4200,
    stock: 10,
    offert: 0,
    tags: ["Limón", "Amapola", "Glaseado", "Cupcake"],
    modalId: "modalCupLimon",
    modalDescription: "Suave bizcochuelo con notas cítricas y textura única, ideal para la merienda.",
    type: "Cupcakes"
  },
  {
    id: 20,
    name: "Cupcake de Chocolate Intenso",
    img: "/uploads/CarruselInicio/CupcakeChoco.png",
    description: "Bizcochuelo de cacao amargo con ganache de chocolate.",
    price: 4300,
    stock: 10,
    offert: 0,
    tags: ["Chocolate", "Ganache", "Cacao amargo", "Cupcake"],
    modalId: "modalCupChoco",
    modalDescription: "Perfecto para amantes del chocolate: sabor intenso y textura húmeda.",
    type: "Cupcakes"
  },
  // ESPECIALES
  {
    id: 21,
    name: "Brownie con Nueces",
    img: "/uploads/CarruselInicio/BrownieNuez.png",
    description: "Brownie de chocolate con trozos de nuez crocante.",
    price: 8500,
    stock: 10,
    offert: 0,
    tags: ["Chocolate", "Nueces", "Brownie"],
    modalId: "modalBrownieNuez",
    modalDescription: "Clásico brownie húmedo con trozos de nuez. Perfecto para los amantes del chocolate y lo crocante.",
    type: "Especiales"
  },
  {
    id: 22,
    name: "Budín de Limón",
    img: "/uploads/CarruselInicio/BudinLimon.png",
    description: "Bizcochuelo húmedo con ralladura y glaseado de limón.",
    price: 6000,
    stock: 10,
    offert: 0,
    tags: ["Budín", "Limón", "Glaseado", "Horneado"],
    modalId: "modalBudinLimon",
    modalDescription: "Budín casero con intenso sabor a limón y cobertura glaseada.",
    type: "Especiales"
  },
  {
    id: 23,
    name: "Cookies Triple Chocolate",
    img: "/uploads/CarruselInicio/CookiesTriple.png",
    description: "Galletas con chips de chocolate blanco, negro y con leche.",
    price: 5500,
    stock: 10,
    offert: 0,
    tags: ["Galletitas", "Chocolate", "Cookies", "Horneado"],
    modalId: "modalCookiesTriple",
    modalDescription: "Galletas crujientes por fuera y suaves por dentro, con explosión de chocolates.",
    type: "Especiales"
  },
  {
    id: 24,
    name: "Cheesecake en Frasco",
    img: "/uploads/CarruselInicio/CheesecakeFrasco.png",
    description: "Crema de queso, base de galletitas y frutos rojos en frasco.",
    price: 6500,
    stock: 10,
    offert: 0,
    tags: ["Queso crema", "Frutillas", "Postre individual", "Frasco"],
    modalId: "modalFrasco",
    modalDescription: "Versión práctica y deliciosa del cheesecake para llevar, en frasco de vidrio reutilizable.",
    type: "Especiales"
  },
  // BOMBONES
  {
    id: 25,
    name: "Bombón de Dulce de Leche",
    img: "/uploads/CarruselInicio/BombonDDL.png",
    description: "Chocolate con corazón de dulce de leche cremoso.",
    price: 3500,
    stock: 10,
    offert: 0,
    tags: ["Chocolate", "Dulce de leche", "Bombón"],
    modalId: "modalBombonDDL",
    modalDescription: "Pequeño placer relleno de dulce de leche artesanal, cubierto con chocolate semiamargo.",
    type: "Bombones"
  },
  {
    id: 26,
    name: "Bombón de Maracuyá",
    img: "/uploads/CarruselInicio/BombonMaracuya.png",
    description: "Relleno frutal ácido con cobertura de chocolate blanco.",
    price: 3700,
    stock: 10,
    offert: 0,
    tags: ["Maracuyá", "Chocolate blanco", "Bombón", "Frutal"],
    modalId: "modalBombonMaracuya",
    modalDescription: "Explosión tropical de sabor con maracuyá fresco y cobertura blanca.",
    type: "Bombones"
  },
  {
    id: 27,
    name: "Bombón Crocante de Avellanas",
    img: "/uploads/CarruselInicio/BombonAvellana.png",
    description: "Relleno de praliné y centro crocante de avellana.",
    price: 3900,
    stock: 10,
    offert: 0,
    tags: ["Avellanas", "Praliné", "Chocolate", "Bombón"],
    modalId: "modalBombonAvellana",
    modalDescription: "Inspirado en los clásicos bombones europeos: textura crocante y sabor a nuez.",
    type: "Bombones"
  }
];

export default products;